# Generated by Django 5.0.6 on 2024-06-26 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_img', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_img', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='featuresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('des', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable', models.CharField(max_length=255)),
                ('customer_details', models.CharField(max_length=255)),
                ('shipping_details', models.CharField(max_length=255)),
                ('trans_ID', models.CharField(max_length=255)),
                ('val_ID', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('delivary_status', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('vat', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_ID', models.CharField(max_length=255)),
                ('store_Password', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('success_URL', models.CharField(max_length=255)),
                ('fail_URL', models.CharField(max_length=255)),
                ('cancel_URL', models.CharField(max_length=255)),
                ('ipn_URL', models.CharField(max_length=255)),
                ('init_URL', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=355)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('shortDes', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('discount', models.BooleanField(default=False)),
                ('discountPrice', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('star', models.CharField(max_length=255)),
                ('stock', models.BooleanField(default=True)),
                ('remark', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brandsmodel')),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('des', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(max_length=255)),
                ('img2', models.CharField(max_length=255)),
                ('img3', models.CharField(max_length=255)),
                ('des', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_address', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('qty', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoicemodel')),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productsmodel')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usersmodel')),
            ],
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usersmodel'),
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('qty', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productsmodel')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WishListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productsmodel')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usersmodel')),
            ],
        ),
    ]
