# Generated by Django 5.0.6 on 2024-06-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsdetailsmodel',
            old_name='des',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productsmodel',
            old_name='title',
            new_name='product_name',
        ),
    ]
