# Generated by Django 5.0.6 on 2024-07-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_brandsmodel_brand_img_alter_featuresmodel_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='remark',
        ),
    ]
